//console.dir(document);
// console.log(document.domain);
// console.log(document.URL);
// console.log(document.title);
// //document.title=123;
// console.log(document.doctype);
// console.log(document.head);
// console.log(document.body);
// console.log(document.all);
// console.log(document.all[10]);
// console.log(document.forms[0]);
// console.log(document.links);
const ul=document.querySelector('.item');
//ul.remove();
//ul.lastElementChild.remove();
ul.firstElementChild.textContent="hello";
